

USE StudentManagement;
GO

DROP TABLE IF EXISTS Students;
GO

CREATE TABLE Students(
	id INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
	Age INT NOT NULL,
	Email VARCHAR(150) NOT NULL,
	EnrollmentDate DATETIME DEFAULT SYSDATETIME());
GO